### ISSUE TITLE
Problem by receiving extended identifiers

### ISSUE THREAD

**Issue by martin7BF** [Longan-Labs/Longan_CANFD#4]
Hello to everyone,

I use this library for reading a can-bus of a lorry/truck. But the extended identifiers bigger than 3FFFF could not be shown right. Their is a mistake in "mcp2518fd_can.cpp" line 2144:

  can_id = ext_flg? (rxObj.bF.id.EID | (rxObj.bF.id.SID << 18)) :  rxObj.bF.id.SID;

should be:

  can_id = ext_flg? (rxObj.bF.id.EID | ((uint32_t) rxObj.bF.id.SID << 18)) :  rxObj.bF.id.SID;

Everythink else is working fine, and I want to thank you for our work, wirting this library.
(And please excause my english)

**Comment by stephen1874** [comment]
thanks for sharing.
